---
- name: add debian source list for jenkis
  copy:
    src: jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list
    mode: 0644

- name: add jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- name: install jenkins
  apt:
    name: jenkins
    state: latest
    update_cache: yes

- name: make sure docker is present
  apt:
    name: docker-ce
    state: present

- name: add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: install apache2
  apt:
    name: apache2
    state: present

- name: enable apache2 proxy module
  apache2_module:
    name: proxy
    state: present

- name: enable apache2 proxy_http module
  apache2_module:
    name: proxy_http
    state: present

- name: disable apache2 default site
  shell: /usr/sbin/a2dissite 000-default

- name: create the jenkins apache config
  copy:
    src: jenkins.conf
    dest: /etc/apache2/sites-available/jenkins.conf

- name: enable jenkins site
  shell: /usr/sbin/a2ensite jenkins

- name: restart apache2
  service:
    name: apache2
    state: restarted
