---
- name: create tomcat group
  group:
    name: tomcat
    system: yes
    state: present

- name: create tomcat user
  user:
    name: tomcat
    system: yes
    shell: /bin/bash
    state: present

- name: download tomcat archive
  get_url:
    url: http://www.trieuvan.com/apache/tomcat/tomcat-8/v8.5.12/bin/apache-tomcat-8.5.12.tar.gz
    dest: /home/tomcat/apache-tomcat-8.5.12.tar.gz

- name: extract tomcat archive
  unarchive:
    src: /home/tomcat/apache-tomcat-8.5.12.tar.gz
    dest: /opt
    remote_src: yes

- name: change ownership for extracted tomcat
  file:
    path: /opt/apache-tomcat-8.5.12
    owner: tomcat
    group: tomcat
    recurse: yes

- name: create tomcat symlink
  file:
    src: /opt/apache-tomcat-8.5.12
    dest: /opt/tomcat
    state: link
    owner: tomcat
    group: tomcat

- name: change mode for webapps directory
  file:
    path: /opt/tomcat/webapps
    mode: 0755

- name: create tomcat service file
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    mode: 0644

- name: enable tomcat to start on boot
  shell: |
    systemctl daemon-reload
    systemctl restart tomcat
    systemctl enable tomcat
