---
- name: install git
  apt:
    name: git
    state: latest
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: remove old docker pakcage
  apt:
    name: docker
    state: absent
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: remove old docker-engine package
  apt:
    name: docker-engine
    state: absent
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install ca-certificates
  apt:
    name: ca-certificates
    state: latest
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install curl
  apt:
    name: curl
    state: latest
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install software-properties-common
  apt:
    name: software-properties-common
    state: latest
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install docker pgp key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: add apt_repository for docker
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  sudo: yes
  sudo_pass: "{{ ssh_password }}"
