---
- name: install apache2
  apt: 
    name: apache2 
    state: latest

- name: enable apache2 proxy module
  apache2_module:
    name: proxy
    state: present

- name: enable apache2 proxy_http module
  apache2_module:
    name: proxy_http
    state: present

- name: disable apache2 default site
  shell: /usr/sbin/a2dissite 000-default

- name: create the http app 8080 apache config
  copy:
    src: 100-http_app_8080.conf
    dest: /etc/apache2/sites-available/100-http_app_8080.conf

- name: enable the http app 8080 site
  shell: /usr/sbin/a2ensite 100-http_app_8080

- name: restart apache2
  service:
    name: apache2
    state: restarted
