---
- name: install apache2
  apt: 
    name: apache2 
    state: latest

- name: enable apache2 proxy module
  apache2_module:
    name: proxy
    state: present

- name: enable apache2 proxy_http module
  apache2_module:
    name: proxy_http
    state: present

- name: disable apache2 default site
  shell: /usr/sbin/a2dissite 000-default

- name: create the jenkins apache config
  copy:
    src: jenkins.conf
    dest: /etc/apache2/sites-available/jenkins.conf

- name: enable jenkins site
  shell: /usr/sbin/a2ensite jenkins

- name: restart apache2
  service:
    name: apache2
    state: restarted
