---
- name: configure sshd to prevent dns resolution
  blockinfile:
    name: /etc/ssh/sshd_config
    block: |
      # Prevent DNS resolution to speed up logins
      UseDNS no

- name: remove 5s grub timeout from config
  lineinfile:
    name: /etc/default/grub
    regexp: '^GRUB_TIMEOUT=[0-9]*$'
    line: 'GRUB_TIMEOUT=0'

- name: upgrade grub
  shell: update-grub

- name: install curl
  apt: 
    name: curl 
    state: latest

- name: install tree
  apt: 
    name: tree 
    state: latest

- name: install sysstat
  apt: 
    name: sysstat 
    state: latest

- name: install ntp
  apt:
    name: ntp
    state: latest

- name: start ntp
  systemd:
    name: ntp
    state: started

- name: enable ntp
  systemd:
    name: ntp
    enabled: yes
