---
- name: install postgresql
  apt: 
    name: postgresql 
    state: latest
  sudo: yes
  remote_user: sbadmin
  sudo_pass: "56@dmin!"

- name: install postgresql-client
  apt: 
    name: postgresql-client 
    state: latest
  sudo: yes
  remote_user: sbadmin
  sudo_pass: "56@dmin!"
