---
- name: create iptables.up.rules
  copy:
    src: iptables.up.rules
    dest: /etc/iptables.up.rules
    mode: 0644
  sudo: yes
  sudo_pass: "{{ ssh_password }}"

- name: make iptables rules are applied on boot
  copy:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
    mode: 0744
  sudo: yes
  sudo_pass: "{{ ssh_password }}"
